name: VMPicker
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  
  - pip=22.1.2
  - numpy=1.24.4
  - scipy=1.10.1
  - pandas=2.0.3
  - matplotlib=3.7.5
  - scikit-learn=1.3.2
  - scikit-image=0.21.0
  - h5py=3.11.0
  - pillow=10.4.0
  - simpleitk=2.4.1
  - tqdm=4.67.1
  - pyyaml=6.0.2
  - cmake=3.31.4
  - ninja=1.11.1.3
  - ipython=7.33.0
  - ipykernel=5.5.5
  - jupyter_client=7.0.6
  - jupyter_core=5.7.2
  - protobuf=4.25.3
  - pytz=2025.1
  - pyparsing=3.1.4
  - regex=2024.11.6
  - typing_extensions=4.12.2
  - pip:
      - absl-py==2.1.0
      - autocommand==2.2.2
      - backcall==0.2.0
      - backports.tarfile==1.2.0
      - cachetools==5.5.2
      - causal_conv1d==1.5.0.post8
      - certifi==2025.1.31
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - einops==0.8.1
      - entrypoints==0.4
      - exceptiongroup==1.2.2
      - filelock==3.16.1
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - huggingface-hub==0.29.1
      - idna==3.10
      - imageio==2.35.1
      - importlib_metadata==8.0.0
      - importlib_resources==6.4.5
      - inflect==7.3.1
      - iniconfig==2.0.0
      - jaraco.context==5.3.0
      - jaraco.functools==4.0.1
      - jaraco.text==3.12.1
      - jedi==0.18.2
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy_loader==0.4
      - lit==18.1.8
      - mamba_ssm==2.2.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - medpy==0.5.2
      - ml-collections==0.1.1
      - more-itertools==10.3.0
      - mrcfile==1.5.4
      - nest_asyncio==1.6.0
      - netron==8.2.5
      - networkx==3.1
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - ordered-set==4.1.0
      - packaging==24.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prompt_toolkit==3.0.43
      - ptyprocess==0.7.0
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.1
      - pycocotools==2.0.7
      - Pygments==2.18.0
      - pytest==8.3.4
      - PyWavelets==1.4.1
      - pyzmq==19.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.5.3
      - segment-anything==1.0
      - setuptools==72.1.0
      - six==1.17.0
      - submitit==1.5.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardX==2.6.2.2
      - termcolor==2.4.0
      - thop==0.1.1.post2209072238
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.4.12
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==1.13.0+cu117
      - torch-tb-profiler==0.4.3
      - torchaudio==0.13.0+cu117
      - torchvision==0.14.0+cu117
      - tornado==6.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==2.0.0
      - typeguard==4.3.0
      - tzdata==2025.1
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - Werkzeug==3.0.6
      - wheel==0.37.1
      - yacs==0.1.8
      - zipp==3.20.2
